name: personel_finance_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/static/Quicksand-SemiBold.ttf
          weight: 600
